version: "3.9"

services:
  laravelapp:
    container_name: back-end
    image: back-endphp
    build: .
    ports:
      - "8081:80"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel-network

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emmy
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel-network

volumes:
  pgdata: {}

networks:
  laravel-network:
    driver: bridge
